name: Publish Docker Image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: docker_build
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_REGISTRY }}/Dockerfile:latest .
          docker login docker.pkg.github.com -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/Dockerfile:latest
        env:
          DOCKER_CLI_AGGREGATE: 1

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
